config/routes.rb
Rails.application.routes.draw do
  resources :records

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  unauthenticated :user do
    root :to => "home#index"
  end

  authenticated :user do
    devise_scope :user do
      get "/" => "records#index"
    end
  end

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    @records = current_user.records.all
    respond_with(@records)
  end

  def show
    respond_with(@record)
  end

  def new
    # @record = Record.new
    # respond_with(@record)
    @record = current_user.records.create
  end

  def edit
  end

  def create
    # @record = Record.new(record_params)
    # @record.save
    # respond_with(@record)
    @record = Record.new(record_params)
    if @record.save
      redirect_to @record
    else
      render 'new'
    end
  end

  def update
    @record.update(record_params)
    respond_with(@record)
  end


  def destroy
    @record.destroy
    respond_with(@record)
  end

  private

  def set_record
    @record = Record.find(params[:id])
  end

  def record_params
    params.require(:record).permit(:title, :artist, :year, :label, :genre, :discs, :tracks, :album_art_url, :user_id)
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :discs %><br>
    <%= f.number_field :discs %>
  </div>
  <div class="field">
    <%= f.label :tracks %><br>
    <%= f.number_field :tracks %>
  </div>
  <div class='field'>
    <%= f.label :album_art_url %><br>
    <%= f.text_field :album_art_url %>
  </div>
  <div class='field'>
    <%= f.hidden_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>My Records</h1>

<%= link_to "Add Record", new_record_path %>

<table id='recordTable' class='table table-striped'>
  <thead>
    <tr class='clickable'>
      <th>Album Art</th>
      <th>Title</th>
      <th>Artist</th>
      <th>Year</th>
      <th>Label</th>
      <th>Genre</th>
      <th>Discs</th>
      <th>Tracks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td id='image'><%= image_tag(record.album_art_url, class: 'album_url') %></td>
        <td><%= link_to "#{record.title}", record %></td>
        <td><%= record.artist %></td>
        <td><%= record.year %></td>
        <td><%= record.label %></td>
        <td><%= record.genre %></td>
        <td><%= record.discs %></td>
        <td><%= record.tracks %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Remove', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div id='image' class='col-md-5'>
    <p>
     <%= image_tag(@record.album_art_url) %>
    </p>
  </div>
  <div class='col-md-4'>
    <p>
      <strong>Title:</strong>
      <%= @record.title %>
    </p>

    <p>
      <strong>Artist:</strong>
      <%= @record.artist %>
    </p>

    <p>
      <strong>Year:</strong>
      <%= @record.year %>
    </p>

    <p>
      <strong>Label:</strong>
      <%= @record.label %>
    </p>

    <p>
      <strong>Genre:</strong>
      <%= @record.genre %>
    </p>

    <p>
      <strong>Discs:</strong>
      <%= @record.discs %>
    </p>

    <p>
      <strong>Tracks:</strong>
      <%= @record.tracks %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>