config/routes.rb
Rails.application.routes.draw do
  resources :records

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  unauthenticated :user do
    root :to => "home#index"
  end

  authenticated :user do
    devise_scope :user do
      get "/" => "records#index"
    end
  end

end

app/models/user_records.rb
class UserRecords < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_records_controller.rb
class UserRecordsController < ApplicationController

  def index
  end

  def new
    @stock = current_user.user_records.build
  end

  def create
    @user_records = User_records.new(user_records.params)
    if @user_records.save
      redirect_to @user_record, notice: 'Record was successfully added'
    else
      render 'new'
    end
  end
end

app/helpers/user_records_helper.rb
module UserRecordsHelper
end

app/views/user_records/index.html.erb
<h1>My User Records</h1>

<%= link_to 'Add Record', new_user_record_path %>

<table id='user_recordTable' class='table table-striped'>
  <thead>
    <tr class='clickable'>
    <th>Album Art</th>
    <th>Title</th>
    <th>Artist</th>
    <th>Year</th>
    <th>Label</th>
    <th>Genre</th>
    <th>Discs</th>
    <th>Tracks</th>
    </tr>
  </thead>

  <tbody>
    <% @user_records.each do |record| %>
      <tr>
        <td id='image'><%= image_tag(record.album_art_url, class: 'album_url') %></td>
        <td><%= link_to "#{record.title}", record %></td>
        <td><%= record.artist %></td>
        <td><%= record.year %></td>
        <td><%= record.label %></td>
        <td><%= record.genre %></td>
        <td><%= record.discs %></td>
        <td><%= record.tracks %></td>
      </tr>
    <% end %>
  </tbody>
</table>